[style]
based_on_style = chromium
spaces_before_comment = 2
split_before_logical_operator = true
indent_width = 2
CONTINUATION_INDENT_WIDTH = 2
DEDENT_CLOSING_BRACKETS = true
SPACES_AROUND_DEFAULT_OR_NAMED_ASSIGN = true
SPLIT_BEFORE_NAMED_ASSIGNS = true
SPLIT_BEFORE_FIRST_ARGUMENT = true
SPLIT_ARGUMENTS_WHEN_COMMA_TERMINATED = true
JOIN_MULTIPLE_LINES = false
SPLIT_COMPLEX_COMPREHENSION = true
EACH_DICT_ENTRY_ON_SEPARATE_LINE = true
ALLOW_SPLIT_BEFORE_DICT_VALUE = true
ALLOW_MULTILINE_DICTIONARY_KEYS = true
